line-length = 100

exclude = [".git/"]

target-version = "py310"

[lint]
select = ["ALL"]
extend-select = ["W", "E"]
preview = true

ignore = [
    "ANN401",  # any-type
    "CPY001", # missing-copyright-notice
    "D205",  # blank-line-after-summary
    "DOC201", # docstring-missing-returns
    "DOC501",  # docstring-missing-exception
    "N818",  # error-suffix-on-exception-name
    "PLC0415", # import-outside-top-level
    "PLC2701", # import-private-name
    "PLR6301", # no-self-use
    "PT009",  # pytest-unittest-assertion
    "PT027",  # pytest-unittest-raises-assertion
    "RUF012",  # mutable-class-default
    "S301",  # 	suspicious-pickle-usage
    "S403",  # 	suspicious-pickle-import
]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.per-file-ignores]
"demos/*" = ["ANN"]
"tests/*" = ["ANN"]

[lint.pylint]
max-args = 7
