services:
  clicker-bot:
    build:
      dockerfile: ./clicker_bot/Dockerfile
    env_file: ./clicker_bot/.env
    depends_on:
      - valkey
    restart: always

  hide-keyboard-bot:
    build:
      dockerfile: ./hide_keyboard_bot/Dockerfile
    env_file: ./hide_keyboard_bot/.env
    depends_on:
      - valkey
    restart: always

  multi-state-bot:
    build:
      dockerfile: ./multi_state_bot/Dockerfile
    env_file: ./multi_state_bot/.env
    depends_on:
      - valkey
    restart: always

  dynamic-keyboard-bot:
    build:
      dockerfile: ./dynamic_keyboard_bot/Dockerfile
    env_file: ./dynamic_keyboard_bot/.env
    depends_on:
      - valkey
    restart: always

  say-hello-bot:
    build:
      dockerfile: ./say_hello_bot/Dockerfile
    env_file: ./say_hello_bot/.env
    depends_on:
      - valkey
    restart: always

  simple-jump-bot:
    build:
      dockerfile: ./simple_jump_bot/Dockerfile
    env_file: ./simple_jump_bot/.env
    depends_on:
      - valkey
    restart: always

  valkey:
    image: valkey/valkey:8.0
    restart: always
    volumes:
      - ./_valkey_data:/data
