name: Linter Runner

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  linter:
    name: Run linter

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run ruff
        run: ruff check . --config=ruff.toml

      - name: Run mypy
        run: mypy --strict .
  tests:
    name: Run tests

    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run demos tests
        run: |
          env HAMMETT_SETTINGS_MODULE=demos.clicker_bot.settings python3 demos/clicker_bot/tests.py
          env HAMMETT_SETTINGS_MODULE=demos.say_hello_bot.settings python3 demos/say_hello_bot/tests.py
          env HAMMETT_SETTINGS_MODULE=demos.simple_jump_bot.settings python3 demos/simple_jump_bot/tests.py

      - name: Run Hammett tests
        run: |
          env HAMMETT_SETTINGS_MODULE=tests.settings coverage run -m unittest discover -s tests/
          coverage report
